#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  SSS-Scanner Installer — Kali Linux
#  Installs sss-scanner to /usr/local/bin for system-wide access
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
TOOL_NAME="sss-scanner"
INSTALL_DIR="/usr/local/bin"
LIB_DIR="/usr/local/lib/sss-scanner"
SCRIPT_NAME="sss-scanner.py"
SOURCE_SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/${SCRIPT_NAME}"

# ── Colors ────────────────────────────────────────────────────────────────────
R="\033[91m"; G="\033[92m"; Y="\033[93m"; C="\033[96m"
W="\033[97m"; B="\033[1m";  D="\033[0m"

ok()   { echo -e "${G}[+]${D} $*"; }
info() { echo -e "${C}[*]${D} $*"; }
warn() { echo -e "${Y}[!]${D} $*"; }
err()  { echo -e "${R}[-]${D} $*"; exit 1; }
sep()  { echo -e "${C}${B}────────────────────────────────────────────────────${D}"; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo
sep
echo -e "  ${B}${W}SSS-Scanner${D}  Installer"
echo -e "  ${D}Target: ${W}${INSTALL_DIR}/${TOOL_NAME}${D}"
sep
echo

# ── Root check ────────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    err "Run as root:  sudo bash install.sh"
fi

# ── Source file check ─────────────────────────────────────────────────────────
if [[ ! -f "${SOURCE_SCRIPT}" ]]; then
    err "${SCRIPT_NAME} not found in current directory.\n    Place install.sh next to ${SCRIPT_NAME} and retry."
fi

# ── Python3 check ─────────────────────────────────────────────────────────────
info "Checking Python3..."
PYTHON_BIN="$(command -v python3 2>/dev/null || true)"
if [[ -z "${PYTHON_BIN}" ]]; then
    warn "python3 not found — installing..."
    apt-get update -qq && apt-get install -y python3 python3-pip
    PYTHON_BIN="$(command -v python3)"
fi
PY_VER="$("${PYTHON_BIN}" --version 2>&1)"
ok "Found ${PY_VER} at ${PYTHON_BIN}"

# ── Install library file ──────────────────────────────────────────────────────
info "Installing to ${LIB_DIR}..."
mkdir -p "${LIB_DIR}"
cp "${SOURCE_SCRIPT}" "${LIB_DIR}/${SCRIPT_NAME}"
chmod 644 "${LIB_DIR}/${SCRIPT_NAME}"
ok "Copied ${SCRIPT_NAME} → ${LIB_DIR}/"

# ── Create launcher wrapper ───────────────────────────────────────────────────
info "Creating launcher at ${INSTALL_DIR}/${TOOL_NAME}..."

cat > "${INSTALL_DIR}/${TOOL_NAME}" <<EOF
#!/usr/bin/env bash
# SSS-Scanner launcher — auto-generated by install.sh
exec ${PYTHON_BIN} "${LIB_DIR}/${SCRIPT_NAME}" "\$@"
EOF

chmod 755 "${INSTALL_DIR}/${TOOL_NAME}"
ok "Launcher created: ${INSTALL_DIR}/${TOOL_NAME}"

# ── Verify it's on PATH ───────────────────────────────────────────────────────
if command -v "${TOOL_NAME}" &>/dev/null; then
    ok "${TOOL_NAME} is on PATH ✓"
else
    warn "${INSTALL_DIR} may not be in your PATH."
    warn "Add this to ~/.bashrc or ~/.zshrc:"
    echo -e "       ${W}export PATH=\"\$PATH:${INSTALL_DIR}\"${D}"
fi

# ── Quick smoke test ──────────────────────────────────────────────────────────
info "Running quick smoke test..."
if "${INSTALL_DIR}/${TOOL_NAME}" --help &>/dev/null; then
    ok "Smoke test passed ✓"
else
    warn "Smoke test returned non-zero — check the script manually."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
sep
ok "${B}Installation complete!${D}"
echo
echo -e "  ${C}Usage:${D}"
echo -e "    ${W}sss-scanner <hosts_file>${D}"
echo -e "    ${W}sss-scanner hosts.txt --mode stealth --cps 20${D}"
echo -e "    ${W}sss-scanner hosts.txt --ports 8080,9090 --timeout 5${D}"
echo
echo -e "  ${C}Uninstall:${D}"
echo -e "    ${W}sudo rm ${INSTALL_DIR}/${TOOL_NAME} && sudo rm -rf ${LIB_DIR}${D}"
echo
sep
echo
